name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint and Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Make format and lint
        run: |
          make fmt
          make lint

      - name: Print runtime versions
        run: |
          node -v || true
          python3 --version || true

      - name: Prompt audit
        run: make prompt-audit

      - name: Config validation
        run: make config-validate

      - name: Bats tests
        run: |
          sudo apt-get update && sudo apt-get install -y bats
          make test:bats

      - name: Security JSON report
        run: make security-json

      - name: Upload security artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-scan
          path: security-scan.json

      - name: Run audit script
        run: bash tools/audit_setup_scripts.sh

      - name: Check script syntax
        run: make test

  security:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for secrets
        run: |
          # Check for actual secret patterns (not just the word "secret")
          if grep -rE "(api[_-]?key|password|token)\s*=\s*[\"'][^\"']+[\"']" --include="*.sh" . | \
             grep -v "example\|template\|placeholder\|\.\.\."; then
            echo "Potential hardcoded secrets found!"
            exit 1
          fi
